spring:
  profiles: dev
  evaluator:
      matching:
          minimumOverlapPercentage: 50.0
      dataaccess:
          uri: http://localhost:9000
  cloud:
    stream:
    #EinAusChannel
      bindings:
        newDataEnvelope:
          destination: wacodis.dataenvelope.creation
          binder: wacodis_rabbit
          content-type: application/json
      #MessageBroker
      binders:
        wacodis_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: eum-dcsi.demo.52north.org
                port: 5672
                username: rabbitmq
                password: rabbitmq
  executor:
      #wps endpoint
      wps:
          uri: http://localhost:9090
          version: 2.0.0
          #define expected process outputs, otherwise defaults (PRODUCT, METADATA) are used
          expectedProcessOutputs:
           - identifier: PRODUCT
             mimeType: image/geotiff
             publishedOutput: TRUE
           - identifier: METADATA
             mimeType: text/json        
             publishedOutput: FALSE
          #define mime type for every input resource, otherwise defaults to text/xml
          #defaultResourceMimeType: text/xml
          #define schema for every input resource, otherwise defaults to GML3
          #defaultResourceSchema:
          #   name: GML3
          #   schemaLocation: http://schemas.opengis.net/gml/3.1.1/base/feature.xsd
---
spring:
  profiles: docker
  evaluator:
    matching:
        minimumOverlapPercentage: 50.0
    dataaccess:
        uri: http://localhost:9000
  cloud:
    stream:
    #InputChannel
      bindings:
        newDataEnvelope:
          destination: wacodis.dataenvelope.creation
          binder: wacodis_rabbit
          content-type: application/json
        jobCreation:
          destination: wacodis.jobs.creation
          binder: wacodis_rabbit
          content-type: application/json
      #MessageBroker
      binders:
        wacodis_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
  executor:
    wps:
        uri: http://localhost:9090
        version: 2.0.0
        #define expected process outputs, otherwise defaults (PRODUCT, METADATA) are used
        expectedProcessOutputs:
         - identifier: PRODUCT
           mimeType: image/geotiff
           publishedOutput: TRUE
         - identifier: METADATA
           mimeType: text/json        
           publishedOutput: FALSE
        #define mime type for every input resource, otherwise defaults to text/xml
        #defaultResourceMimeType: text/xml
        #define schema for every input resource, otherwise defaults to GML3
        #defaultResourceSchema:
        #   name: GML3
        #   schemaLocation: http://schemas.opengis.net/gml/3.1.1/base/feature.xsd