spring:
  profiles: dev
  evaluator:
      matching:
          minimumOverlapPercentage: 50.0
      dataaccess:
          uri: http://localhost:9000
  cloud:
    stream:
    #EinAusChannel
      bindings:
        newDataEnvelope:
          destination: wacodis.dataenvelope.creation
          binder: wacodis_rabbit
          content-type: application/json
      #MessageBroker
      binders:
        wacodis_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: eum-dcsi.demo.52north.org
                port: 5672
                username: rabbitmq
                password: rabbitmq
  executor:
      cleanUpTool: cleanUpProcessID
      #wps endpoint
      wps:
          uri: http://localhost:9090
          version: 2.0.0        
---
spring:
  profiles: docker
  evaluator:
    matching:
        minimumOverlapPercentage: 50.0
    dataaccess:
        uri: http://localhost:9000
  cloud:
    stream:
    #InputChannel
      bindings:
        newDataEnvelope:
          destination: wacodis.dataenvelope.creation
          binder: wacodis_rabbit
          content-type: application/json
        jobCreation:
          destination: wacodis.jobs.creation
          binder: wacodis_rabbit
          content-type: application/json
      #MessageBroker
      binders:
        wacodis_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
  executor:
    cleanUpTool: cleanUpProcessID
    wps:
        uri: http://localhost:9090
        version: 2.0.0
