spring:
  profiles: dev
  resources-api:
    elasticsearch:
      uri: http://localhost:9200
      indexName: dataenvelope
      requestTimeout_Millis: 5000

  rabbitmq:
    host: eum-dcsi.demo.52north.org
    port: 5672
    username: rabbitmq
    password: rabbitmq
     
---
spring:
  profiles: docker
  resources-api:
    elasticsearch:  
      uri: http://localhost:9200
      indexName: dataenvelope
      requestTimeout_Millis: 5000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest                