spring:
  profiles: dev
  resources-api:
    elasticsearch:
      uri: http://localhost:9200
      indexName: dataenvelope
      requestTimeout_Millis: 5000
  dataenvelopes-api:
    elasticsearch:
      uri: http://localhost:9200
      indexName: dataenvelope
      type: dataenvelope
      requestTimeout_Millis: 5000
      indexInitialization_RetryMaxAttempts: 5
      indexInitialization_RetryDelay_Millis: 15000
      indexInitialization_SettingsFile: ./src/main/resources/elasticsearch_indexsettings.json
  cloud:
    stream:
      bindings:
        acknowledgeDataEnvelope:
          destination: wacodis.dataenvelope.acknowledgment
          binder: wacodis_rabbit
          content-type: application/json
      binders:
        wacodis_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: rabbitmq
                password: rabbitmq
     
---
spring:
  profiles: docker
  resources-api:
    elasticsearch:  
      uri: http://localhost:9200
      indexName: dataenvelope
      requestTimeout_Millis: 5000
  dataenvelopes-api:
    elasticsearch:
      uri: http://localhost:9200
      indexName: dataenvelope
      type: dataenvelope
      requestTimeout_Millis: 5000
      indexInitialization_RetryMaxAttempts: 5
      indexInitialization_RetryDelay_Millis: 15000
      indexInitialization_SettingsFile: ./src/main/resources/elasticsearch_indexsettings.json
  cloud:
    stream:
      bindings:
        acknowledgeDataEnvelope:
          destination: wacodis.dataenvelope.acknowledgment
          binder: wacodis_rabbit
          content-type: application/json
      binders:
        wacodis_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
