spring:
  profiles: dev
  resources_api:
    elsasticsearch:
      uri: http://localhost:9200
      indexName: dataenvelope
      requestTimeout_Millis: 5000
  cloud:
    stream:
      #MessageBroker
      binders:
        wacodis_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: eum-dcsi.demo.52north.org
                port: 5672
                username: rabbitmq
                password: rabbitmq
     
---
spring:
  profiles: docker
  resources_api:
    elasticsearch:  
      uri: http://localhost:9200
      indexName: dataenvelope
      requestTimeout_Millis: 5000
  cloud:
    stream:
      binders:
        wacodis_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest                