spring:
  profiles: dev
  execution:
    interval:
      #all values in seconds
      # 1 hour
      sensorWeb: 3600
      sentinel: 3600
      dwd: 3600
      # 1 day
      maxInterval: 86400 
  cloud:
    stream:
    #EinAusChannel
      bindings:
        jobCreation:
          destination: wacodis.jobs.creation404
          binder: wacodis_rabbit
          content-type: application/json
        outputDataEnvelope:
          destination: wacodis.dataenvelope.creation
          binder: wacodis_rabbit
          content-type: application/json
      #MessageBroker
      binders:
        wacodis_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: eum-dcsi.demo.52north.org
                port: 5672
                username: rabbitmq
                password: rabbitmq
     
---
spring:
  profiles: docker
  execution:
    interval:
      #all values in seconds
      # 1 hour
      sensorWeb: 3600
      sentinel: 3600
      dwd: 3600
      # 1 day
      maxInterval: 86400 
  cloud:
    stream:
    #EinAusChannel
      bindings:
        jobCreation:
          destination: wacodis.jobs.creation404
          binder: wacodis_rabbit
          content-type: application/json
        outputDataEnvelope:
          destination: wacodis.dataenvelope.creation
          binder: wacodis_rabbit
          content-type: application/json
      #MessageBroker
      binders:
        wacodis_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: eum-dcsi.demo.52north.org
                port: 5672
                username: rabbitmq
                password: rabbitmq                